### ISSUE TITLE
Adds T00:00:00+00:00 after date in YYYY-MM-DD format 

### ISSUE THREAD

**Issue by amberjewel** [harvard-library/aspace-import-excel#9] opened 2017-09-19 17:18 UTC
We're testing this plugin for use with a large spreadsheet and noticed that the Begin Date and End Date fields end up with T00:00:00+00:00 in ArchivesSpace after the date in YYYY-MM-DD format. This doesn't happen for YYYY or YYYY-MM date types.

Is there a workaround or something we're doing wrong that's causing this? I can clean it up in the EAD after export but would prefer to not have it in AS in the first place if possible.

Thank you!

**Comment by bobbi-SMR** [comment] 2017-09-19 17:28
Hi,

I'll take a look at this ASAP, and get back to you; the code may not be triggering the correct conversion algorithm.

**Comment by bobbi-SMR** [comment] 2017-09-19 17:46
@amberjewel : With the very small test case I created 
[test_dates.xlsx](https://github.com/harvard-library/aspace-import-excel/files/1315257/test_dates.xlsx)
I was unable to reproduce your issue.  Which version of ArchiveSpace are you working with?  Would you be able to attach an example of your spreadsheet?

Thanks,
Bobbi

**Comment by amberjewel** [comment] 2017-09-19 18:46
We're working with v.1.5.4 at the moment. I'm attaching our test
spreadsheet that we used.

Thank you!
Amber

**Comment by bobbi-SMR** [comment] 2017-09-19 18:48
Hi, the attachment didn't come through :-(

(I tested on v1.5.3, btw, but that shouldn't have mattered...)

**Comment by amberjewel** [comment] 2017-09-19 18:51
I've attached it again. Hopefully it will go through this time. It looks
like it's successfully attached to the e-mail. I can try it another way if
need be.

**Comment by amberjewel** [comment] 2017-09-19 18:52
[aspace_import_excel_test2.xlsx](https://github.com/harvard-library/aspace-import-excel/files/1315504/aspace_import_excel_test2.xlsx)

**Comment by amberjewel** [comment] 2017-09-19 18:52
There we go. I'm adjusting to GitHub as a user - I've only ever lurked before.

**Comment by bobbi-SMR** [comment] 2017-09-19 18:53
Got it!  I may not be able to get back to you before tomorrow.

Cheers,

**Comment by amberjewel** [comment] 2017-09-19 18:55
Thank you. We're trying to test this every which way before we go live with the plugin, and I appreciate any assistance.

**Comment by bobbi-SMR** [comment] 2017-09-19 19:59
Testing every which way is a good idea 😄 
Here's what I see so far:
In _my_ tiny test, the date cell is formatted as "general".

In _your_ spreadsheet, the date cell is formatted as "Custom" "Type: _yyy-mm-dd_"  I'm not an excel guru (she's out today 🙁 ), so I don't know what the customizing does, but perhaps behind the scenes those yyy-mm-dd becomes a DateTime object, resulting in that time information being included when my code comes to process it, whereas perhaps when it's general, it comes through to my code as a date simple string?

I see that when *I* try to add a row in your spreadsheet, it converts 1984-04-06 to a Date, no matter what I do about it!  This doesn't happen with my spreadsheet; I don't know enough about Excel to know how to turn it off!

Hopefully tomorrow I can grab a small amount of our Excel guru's time, because if we can figure out how to turn that off, it will go faster for you than waiting for me to make a change in the ingest code, test it, put it up on GitHub, etc.

Til tomorrow,
Bobbi

**Comment by amberjewel** [comment] 2017-09-19 20:06
Hi Bobbi,

Thanks! We've been having trouble with the date fields for the exact same
reason. Our Excel guru hasn't been able to turn off the automatic date
feature, so I hope yours has some suggestions.

Thank you again for looking into this!
Amber

**Comment by bobbi-SMR** [comment] 2017-09-19 20:25
Hi, Amber,

Just as I was getting ready to go home for the night, a different Excel guru cruised by.

She suggested that the automatic date stuff might be caused by you using a different version of Excel than the one we used to create the template.  Some investigation showed that the begin and end date columns are defined in our template as having the format "General"; if the columns are set to "Text", the automatic date stuff doesn't happen!

It will take me a little while tomorrow to get the enhanced template up on github (there is a vetting process, like doing some testing, you know 😃 ).  Be warned that if (at least in the version of Excel I'm using) you change the formatting of those columns with cells of the YYYY-MM-DD format already entered, you'll get some **VERY** strange results.

**Comment by amberjewel** [comment] 2017-09-19 22:26
Hi Bobbi,

Thanks! I was starting suspect a version issue might be at the heart of the
situation. I was playing around with those dates and also got the very
strange results when I tried to change them to general with the dates
already inside. Excel has some crazy quirks.

By the way, I just tested the plugin with an almost 12,000 row spreadsheet,
and I have to say that this plugin is fantastic. I appreciate all of the
work that went into it because it's making the work at our small shop
infinitely easier for a huge finding aid on a tight deadline.

**Comment by bobbi-SMR** [comment] 2017-09-20 18:26
Hi, Amber,

In one of those "D'OH!" moments, it occurred to me that I could upload the revised template here, so you could try it out.  Here you go!  You Get It First 😃 
[aspace_import_excel_template.xlsx](https://github.com/harvard-library/aspace-import-excel/files/1318791/aspace_import_excel_template.xlsx)

_And thanks for your kind words; it's so rewarding to be working on something people actually use and need._

**Comment by amberjewel** [comment] 2017-09-20 18:56
Thank you! I might have a chance to try it out this afternoon.

**Comment by amberjewel** [comment] 2017-09-25 15:13
I wanted to let you know that we did get a chance to check out the new
version of the spreadsheet, and our versions of Excel did not override the
date columns this time around, so using Text instead of General was a
definite success.

I haven't had a chance to get a spreadsheet into our test instance of AS,
though, because systems is testing the upgrade to 2.0 at the moment. Out of
curiosity, do you have any idea if the plugin will work with 2.0 or above?

**Comment by bobbi-SMR** [comment] 2017-09-25 15:17
Hi, Amber,

The plugin should work with 2.x (at least I coded it to do so, and tested it locally!).

Cheers,
Bobbi

**Comment by amberjewel** [comment] 2017-09-25 15:28
Hi Bobbi,

That's great to hear. Once again, you have my deepest appreciation for what
you have done here with this plugin.

Cheers!
Amber

**Comment by amberjewel** [comment] 2017-09-27 17:02
Hi Bobbi,

I have a follow-up question about the plugin. We were able to load a
spreadsheet of almost 12,000 rows once successfully but since then have
kept bumping into what seems to be a time-out error of some sort as we test
further. This doesn't happen with spreadsheets of 5000 rows or fewer. Are
there any settings in any of the code or in AS that we might be able to
manipulate to avoid that?

We can break the spreadsheet into smaller chunks if need be, but I thought
I'd check first since it did work once. When it worked our test instance
was still on v1.5.4 but now is on v2.0. Systems is going to upgrade us to
v2.1.2 soon to see if that has any impact.

I appreciate any insight you might have.
Amber

**Comment by pobocks** [comment] 2017-09-27 18:16
Hi Amber,

I'm Dave, a co-worker of Bobbi's.  Would you be able to provide us with the spreadsheet?

I think what's happening is that you're hitting the time-out just because something in 2.x got slower or similar, and just fell past the boundary.  I'd like to verify this; it certainly might be something else, after all.  If that _is_ the problem, chunking it up is probably the right move; I don't think there's really a meaningful way to stream-process Excel files, afaik.

**Comment by amberjewel** [comment] 2017-09-27 18:20
Hi Dave,

I'm attaching the latest version of the spreadsheet. Thank you for looking
into this.

**Comment by pobocks** [comment] 2017-09-27 19:09
Hmm, if it's attached here, I think github swallowed it - if you want to email it to dave UNDERSCORE mayo AT harvard DOT com, I'll poke at it (maybe tomorrow!)

**Comment by randystern** [comment] 2017-09-27 19:58
At harvard DOT edu, that is!

**Comment by bobbi-SMR** [comment] 2017-09-28 20:16
I've committed the template spreadsheet; now at v1.4.

**Closed as completed by bobbi-SMR** 2017-09-28 20:16 UTC
