### ISSUE TITLE
[Unknown child node [xr:revisionPtr] for element [workbook]]

### ISSUE THREAD

**Issue by mmwisner** [harvard-library/aspace-import-excel#35] opened 2018-06-19 18:33 UTC
I'm receiving this error message consistently, having checked my spreadsheet over to the best of my ability. I attach the spreadsheet.
[PromptbooksImport2.xlsx](https://github.com/harvard-library/aspace-import-excel/files/2116438/PromptbooksImport2.xlsx)

Apologies and thanks!

**Comment by bobbi-SMR** [comment] 2018-06-20 15:12
Hi, Melanie,

I’ve had other crises to deal with in the past day; I’ll be looking at this now.

Cheers,
Bobbi

**Comment by bobbi-SMR** [comment] 2018-06-20 16:15
We have confirmed (out of band) that the problem is with an Excel spreadsheet produced using the online version of Office 2016.  I will be investigating solutions.

**Comment by releach** [comment] 2018-07-16 22:30
Same issue here. I've been working around this by pasting the template into Google Sheets, adding data there, and then saving/downloading as an xlsx.

**Comment by nikkibo77** [comment] 2018-08-12 16:56
Checking in to see if there's any progress on a solution to this bug?  I'm having the same problem.

**Comment by bobbi-SMR** [comment] 2018-08-13 17:31
I think that the library upon which I was depending (FubyXL) has now been updated (this is just a guess; I'm not seeing documentation to that effect).  However, since I don't have this version of MSExcel myself:  would you kindly upload an example spreadsheet? 

 I think that if I directly download it, it retains its versioning (if I open it and then save it, it will be in the version I have on my desktop).  When you do the upload, please tell me the EADID you're using, so I can create a dummy Resouce in my system.

Thanks,
Bobbi

**Comment by nikkibo77** [comment] 2018-08-14 03:31
[NBS_Directories_Import.xlsx](https://github.com/harvard-library/aspace-import-excel/files/2285401/NBS_Directories_Import.xlsx)

I used Directories_EAD as my EADID.

Thanks for looking into it!

**Comment by bobbi-SMR** [comment] 2018-08-15 19:17
Hi,

I think that my fix is working (or at least your spreadsheet was processed :-), but I have another question that I'd rather ask via email, since it's unrelated to this issue. (Depending on your answer, I might have One More Change to make before releasing the new version).

 Would you be willing to contact me at bobbi_fox AT harvard.edu?

Thanks.

**Comment by bobbi-SMR** [comment] 2018-08-24 18:05
Fixed with release v2.1.11

**Closed as completed by bobbi-SMR** 2018-08-24 18:05 UTC
Labels: bug
